name: Test Restricted Deploy

on:
  workflow_dispatch:  # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building app..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Deploying app as ${{ github.actor }}"
